# Generated by Django 6.0.3 on 2026-03-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homebanner')),
                ('image1', models.ImageField(upload_to='homebanner')),
                ('image2', models.ImageField(upload_to='homebanner')),
            ],
        ),
        migrations.CreateModel(
            name='Bannerdestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bimg', models.ImageField(upload_to='destination')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('dimg', models.ImageField(upload_to='destination')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Timg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd', models.ImageField(upload_to='homeminiimg')),
                ('hs', models.ImageField(upload_to='homeminiimg')),
                ('tt', models.ImageField(upload_to='homeminiimg')),
                ('ht', models.ImageField(upload_to='homeminiimg')),
            ],
        ),
    ]
