# Generated by Django 6.0.3 on 2026-03-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='dimg1',
            field=models.ImageField(blank=True, null=True, upload_to='destination'),
        ),
        migrations.AddField(
            model_name='destination',
            name='dimg2',
            field=models.ImageField(blank=True, null=True, upload_to='destination'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='homebanner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='homebanner'),
        ),
    ]
