# Generated by Django 6.0.3 on 2026-03-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_destination_dimg1_destination_dimg2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timg',
            name='hs',
            field=models.ImageField(blank=True, null=True, upload_to='homeminiimg'),
        ),
        migrations.AlterField(
            model_name='timg',
            name='ht',
            field=models.ImageField(blank=True, null=True, upload_to='homeminiimg'),
        ),
        migrations.AlterField(
            model_name='timg',
            name='pd',
            field=models.ImageField(blank=True, null=True, upload_to='homeminiimg'),
        ),
        migrations.AlterField(
            model_name='timg',
            name='tt',
            field=models.ImageField(blank=True, null=True, upload_to='homeminiimg'),
        ),
    ]
