# Generated by Django 6.0.3 on 2026-03-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_timg_hs_alter_timg_ht_alter_timg_pd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
