# Generated by Django 6.0.3 on 2026-03-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_destination_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='duration',
            field=models.CharField(blank=True, default='not-mention', max_length=50),
        ),
    ]
