# Generated by Django 6.0.3 on 2026-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_destination_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='includes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
