# Generated by Django 6.0.3 on 2026-03-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='cont',
        ),
    ]
