# Generated by Django 6.0.3 on 2026-03-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='description',
            new_name='gdesc',
        ),
        migrations.AddField(
            model_name='gallery',
            name='gimg1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='gimg2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='gimg3',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='gimg4',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
