# Generated by Django 6.0.3 on 2026-03-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_description_gallery_gdesc_gallery_gimg1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='hb'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='hb'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='hb'),
        ),
        migrations.AlterField(
            model_name='bannerdestination',
            name='Bimg',
            field=models.ImageField(upload_to='bd'),
        ),
        migrations.AlterField(
            model_name='timg',
            name='hs',
            field=models.ImageField(blank=True, null=True, upload_to='mhb'),
        ),
        migrations.AlterField(
            model_name='timg',
            name='ht',
            field=models.ImageField(blank=True, null=True, upload_to='mhb'),
        ),
        migrations.AlterField(
            model_name='timg',
            name='pd',
            field=models.ImageField(blank=True, null=True, upload_to='mhb'),
        ),
        migrations.AlterField(
            model_name='timg',
            name='tt',
            field=models.ImageField(blank=True, null=True, upload_to='mhb'),
        ),
    ]
