# Generated by Django 6.0.3 on 2026-03-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_booking_created_at_booking_price_per_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='QR',
            field=models.ImageField(blank=True, null=True, upload_to='qr'),
        ),
    ]
