# Generated by Django 6.0.3 on 2026-04-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_booking_vehicle_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gimg1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gdesc',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gimg',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gimg2',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gimg3',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gimg4',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('hill', 'Hill Station'), ('beach', 'Beach'), ('temple', 'Temple'), ('city', 'City'), ('forest', 'Forest')], default='city', max_length=50),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
