# Generated by Django 6.0.3 on 2026-04-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_gimg1_gallery_image_remove_gallery_gdesc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
