# Generated by Django 6.0.3 on 2026-04-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_gallery_image1_gallery_image2_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('hill', 'Hill Station'), ('beach', 'Beach'), ('temple', 'Temple')], default='city', max_length=50),
        ),
    ]
