# Generated by Django 6.0.3 on 2026-04-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_gallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
