# Generated by Django 6.0.3 on 2026-04-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_destination_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='location',
        ),
    ]
