# Generated by Django 6.0.3 on 2026-04-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('hill', 'Hill Station'), ('beach', 'Beach'), ('temple', 'Temple')], default='hill', max_length=50),
        ),
    ]
