# Generated by Django 6.0.3 on 2026-04-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_profile_bio_remove_profile_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
