# Generated by Django 6.0.3 on 2026-04-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bannerdestination',
        ),
    ]
