# Generated by Django 6.0.3 on 2026-04-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_delete_bannerdestination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[], default='hill', max_length=50),
        ),
    ]
